### ISSUE TITLE
update readme to include getting started steps

### ISSUE THREAD

**Issue by hcientist** [JMU-CS/Thought-Swap#1]
1. clone project from github
1. install mysql (if mac use homebrew)
    1. (optional) install MySQLWorkbench
1. install node (if mac use homebrew)
1. install dependencies for server application (`npm install` when in same dir as `package.json`)
1. create a database in your (local) mysql server for thoughtswap (maybe using MySQL WorkBench)
1. create a (non-root) database user in mysql that can access the thoughtswap database schema you just created (maybe using MySQL WorkBench)
1. create environemnt varibales with the names expected in `app.models.js` that have the correct values for the schema and user you created in mysql

also update readme to tell yourself and any future colleagues how to launch the server, how to register a user, create a group, etc.

**Comment by brittanybraswell** [comment]
I added this to the readme, but let me know if something is off or something needs to be added.
