### ISSUE TITLE
+1 participant button does not work

### ISSUE THREAD

**Issue by hcientist** [JMU-CS/Thought-Swap#5]
server issue

**Comment by brittanybraswell** [comment]
Yeah the +1 participant button doesn't seem to work on my local machine, but it does work on the thought swap website.

**Comment by brittanybraswell** [comment]
We updated sequelize to v4 recently, so some of the syntax we have is wrong. For this particular issue, we were using instance methods from sequelize.define, but that's no longer supported. I removed that instance method and used a prototype method instead. The +1 participant button now works on my local machine.
