### ISSUE TITLE
content width is inconsistent

### ISSUE THREAD

**Issue by hcientist** [JMU-CS/Thought-Swap#9]
remove the max-width 660 in styles.css

see: 
https://github.com/JMU-CS/Thought-Swap/blob/develop/client/styles.css#L454
https://github.com/JMU-CS/Thought-Swap/blob/develop/client/styles.css#L526

**Comment by brittanybraswell** [comment]
Those two lines were commented out. I also resized the images on the help page because they were too large after max-width 660 was removed.
